DD-272 Updating dependencies
HMPO/hmpo-reqres pull request #2
Opened 2024-10-01 09:36 UTC by imran-gov

Updated the following dependencies:
express ^4.19.2 -> ^4.21.0
sinon ^18.0.0 -> ^19.0.2
eslint ^9.9.0 -> ^9.11.1

2024-10-01 09:46 UTC, SamChatfield requested changes
Let's update the package `engines` to match the other libs

2024-10-01 09:46 UTC, SamChatfield commented on package.json
>    "devDependencies": {
Need `husky` added and set up with pre-push hook

2024-10-02 08:25 UTC, SamChatfield commented on package.json
>    "devDependencies": {
We're still missing the husky `prepare` package script meaning `npx husky init` hasn't been run

2024-10-02 09:01 UTC, imran-gov commented on package.json
>    "devDependencies": {
thanks Sam, updated now

2024-10-02 13:31 UTC, cmcgee480 approved these changes

2024-10-03 15:25 UTC, SamChatfield approved these changes
LGTM

2024-10-10 08:17 UTC, merged